- name: demo on loops
  hosts: local
  connection: local

  tasks:
  - name: loop the variables
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop:  #list of string
      - Naga  #string
      - Ajay
      - Bhartah

