# we generally use filters conv string to list

- name: demo on filters
  hosts: local
  connection: local

  vars:                                           # resrved keyword       
    topics: linux, shell, ansible, terraform     #topic is a string

    tags_map:                         # reserved keyword
      Name: Naga
      course: DevSecOps with AWS
    tags_list: [
    
          {
              "key": "Name",
              "value": "Naga"
          },
          {
              "key": "course",
              "value": "DevSecOps with AWS"
          }
      ]

  tasks:
  - name: Greeting filter
    ansible.builtin.debug:
      msg: "Hi, Naga {{ Greeting | default('good morning')}}"

  - name: convert from string to list     #convert string (topics) to list
    ansible.builtin.debug:
      msg: "{{ topics | ansible.builtin.split(',') }}"

  - name: convert from map to list     #convert map (tags_map) to list
    ansible.builtin.debug:
      msg: "{{ tags_map | dict2items }}"

  - name: convert from map to list     #convert list (tags_list) to map
    ansible.builtin.debug:
      msg: "{{ tags_list | items2dict }}"
