- name : file level variables kept variables in seperate yaml
  host: local
  connection: local
  become: yes
  vars_files:
  - course.yaml
  tasks:
  - name: printing varaibles 
    ansible.builtin.debug:
      msg: "doing is : {{doing}} , experience is : {{experience}}"